# Generated by Django 5.2.6 on 2025-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('bibliotecario', 'Bibliotecário'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
    ]
